In [4]:
import numpy as np
import sys

In [6]:
#Array 1D
a1 = np.array([1,2,3,4,5])
#Array 1D
a1d2 = np.array([1,2,3,4,5])

In [20]:
#Array 2D
a2 = np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#Array 3D
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [12]:
#Soma de arrays
sum = np.add(a1, a1d2)
sum

array([ 2,  4,  6,  8, 10])

In [24]:
#Selecionar um valor dentro da array
# array[row, column]
a2[0,2]

3

In [28]:
a2[1:]

array([[4, 5, 6]])

In [35]:
a2[:,2]

array([3, 6])